### PR TITLE
Add support for windows

### PR DESCRIPTION
**Pull request by reds-heig**
## Description 

This PR implement compilation support for `flagser`.

## What's does it implement

- [x] Implement compilation and execution of `flagser` on Windows
- [x] Compiles and work on Linux
- [x] Currently passes 17/17 test (UPDATED)
- [ ] 0 warnings with windows compilation

## Current Issues

:warning: FIXED :warning: 

I have a 16 of 17 test passing, at the moment 1 cannot pass:

`medium-test-data.flag`, produces only on Windows the following error:

```
dim H_0 = 20726                                                                                                         
Could not find coboundary 83|0|209 .                                                                  
Could not find coboundary 82|3|12 .                                                                                   
Could not find coboundary 22|15|394 .                                                                                 
Could not find coboundary 274|2|478 .
```

Any help or hint could help me a lot to find a solution why only one test is failing.

## Remaining

I only tested `flagser` because there's only test written for it. Maybe adding more test to the other functionalities could make more robust PR ?

Cheers,
Julián

### CODE REVIEW

**Comment by reds-heig** [comment]
Last commit fixes the described issue.
The problem was a difference between `1UL` on UNIXes systems and windows.
This problem was reported on [SO](https://stackoverflow.com/questions/57212719/bitwise-operation-left-shift-in-msvc-is-diffrent-from-linux-gcc/57213178#57213178)

Now all tests passes:

* [x]  Currently passes 17/17 test


Remaining work would be to get ride of all the warning, but unfortunately I cannot do it at the moment

Julián

**Comment by luetge** [comment]
I added some automatic tests on different platforms, everything passes on Windows. Thanks for making the effort to fixing the bugs! I will remove all warnings one of these days, if it is urgent to you feel free to open another pull request. Thanks!

**Comment by MonkeyBreaker** [comment]
Hi @luetge,

Sorry for my delayed answer, I was on Holiday.
Thank you for merging PR and added more tests, it's really useful.

For the warnings, it can hide an untested problem, let see if any user report a bug :)

Julián

**Comment by luetge** [comment]
Hi,

I brought it down to a single warning (but a huge one), if you know how to fix that I would appreciate it, otherwise I might merge the new branch even with that one warning and fix it at a later point.

https://travis-ci.com/luetge/flagser/jobs/283312066

Cheers,
Daniel

**Pull request merged**
